### ISSUE TITLE
User feedback when they're editing a menu that doesn't exist in the preview

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#10]
We should look into displaying some sort of a warning in/over the preview when a user is editing a menu that isn't in the preview. Menus can be in both theme locations and widgets, so if the active menu section isn't anywhere in either, this tip can help users understand how to make their menu show up on their site.

**Comment by celloexpressions** [comment]
@westonruter do you think this is something we can realistically do with the timeframe we have?

**Comment by westonruter** [comment]
It is already possible to do this given what I've added in https://github.com/xwp/wp-customize-partial-refresh/pull/12

All instances of menus are exported to JS in `wp.customize.partialPreviewMenus.pane.navMenuInstanceArgs`

Whenever a menu setting gets update, it calls `wp.customize.partialPreviewMenus.preview.refreshMenu( menuId )`.

So the change here would be that if no match is found in this loop:

```js
_.each( self.navMenuInstanceArgs, function ( navMenuArgs, instanceNumber ) {
	if ( menuId === navMenuArgs.menu ) {
		self.refreshMenuInstance( instanceNumber );
	}
} );
```

That the preview could then show a message.

But… wouldn't it be better to hook into `activeSections` and just make the menu section not appear at all?

**Comment by celloexpressions** [comment]
The problems with menus are that they can be assigned to different locations in the UI, basically making them show up or be hidden, so we can't really hide them if they aren't shown in the preview. But thinking about it, it may make sense to make the menu location controls contextual, although that probably isn't worth it. So maybe the only issue here would be adding something to highlight what menu they're working on if it's in the preview, but we may not even need that at this point.
