### ISSUE TITLE
Accessibility: consider improving some focus styles

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#100]
Not sure it's an intentional design, worth considering though. For example the menu options and help icons in Firefox have just the color change while Webkit shows its own native focus style:

![Webkit can fool us]
(https://cldup.com/QeVfa6HpHB.png)

**Comment by celloexpressions** [comment]
Oops, didn't realize that that one was relying on browser defaults. It was designed out to have the outline as indicated on the left. Fixing now.

**Comment by celloexpressions** [comment]
Please open additional issues if you find any more of these.
