### ISSUE TITLE
Custom Link items should have view links also

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#104]
We have handy "original" links for items that represent post or taxonomy term objects. We should add similar functionality for custom links and for bonus points, make it open in the Customizer preview if it's a previewable URL or otherwise open it in a new tab. Currently your best workflows are to copy/paste the URL or click on the link in the preview (which wouldn't work if it is an external link).

**Comment by westonruter** [comment]
Note that original links for external custom links won't work in the Customizer either, since the Customizer preview will reject previewing any URL that is not under the site.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32711
