### ISSUE TITLE
Accessibility: buttons don't need keyboard events, e.g. Add Links and Reorder

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#107]
"Add Links" is a button and as such can be activated with both the Enter key and the Spacebar. When using Enter, all is fine. When using the Spacebar:
- the search field gets a space character
- hence, the placeholder text is gone
- a search is triggered (notice the spinner in the screenshot below)

Screenshot using Enter (above) and Spacebar (below)

![Add Links with Enter or Spacebar]
(https://cldup.com/VsTEkToyp2.png)

That's because the Add Links button has an unnecessary keydown event and no event.preventDefault(), so the default action of entering a space is executed. Also, the search shouldn't fire when there are just leading space characters.

Buttons don't need keyboard events, they natively support keyboard interaction and they just need a click event. Suggestion: in `api.Menus.MenuControl._setupAddition` just remove the keydown event and the check for Enter or Spacebar,
Additionally, when used as UI controls and not to submit forms, buttons need to always have a `type="button"` attribute specified and you don't even need to use `preventDefault()` because there's no default action to prevent.

Same for the Reorder button: currently can't be used with a keyboard. Pressing Enter does nothing, pressing the Spacebar makes the reordering arrows appear and suddenly disappear. Just removing the keydown event and check fixes it.

Would recommend to check all the buttons and remove keydown events unless they're used for a very particular reason (I can't think of a valid use case though).

**Comment by afercia** [comment]
One more example is the "Delete menu" button, when activated with Enter makes the JavaScript alert appear twice. Just remove the keydown event.

**Comment by designsimply** [comment]
Sounds similar to #83.
