### ISSUE TITLE
Finish re-implementing accessible touch-friendly reordering

### ISSUE THREAD

**Issue by westonruter** [voldemortensen/menu-customizer#111]
With the re-architecture of the Customizer settings in #67 (PR #73), the way that menus and their items are represented became incompatible with the previous implementation of the functionality. Now that all of the items have their settings data stored in memory, we can update the reordering controls to just manipulate the models and the controls in the menu need to then reflow to their proper locations. 

This is split out from #4.

**Comment by designsimply** [comment]
Screenshot for reference: the accessible touch-friendly reordering = the "Reorder" link that sits below the menu to the left of the `+ Add Items` button:

![screen shot 2015-06-15 at mon jun 15 12 43 14 pm](https://cloud.githubusercontent.com/assets/1119271/8165211/89607e50-135c-11e5-9543-6dcde83a2b0a.png)
<sup>Seen at `/wp-admin/customize.php` tested with WP 4.3-alpha-32784 and Menu Customizer plugin 0.6-df789de using Firefox 38.0.5 on Mac OSX 10.10.3</sup>
