### ISSUE TITLE
Multiple Drag n Drop issues

### ISSUE THREAD

**Issue by maddisondesigns** [voldemortensen/menu-customizer#113]
When dragging 'n dropping a menu items, if you move the menu item up even 1px, it wont drop into place properly. You can see in the following gif when I move the menu item vertically by 1px, you'll notice the dotted line behind it (indicating where it's going to drop), constanty moves back to its original location.
https://cloudup.com/cA9dfVld6w2

As soon as you move a single menu item, the live preview breaks
https://cloudup.com/cdBFOgmxPvl

Can't move certain submenus up a level. As you can see in the following gif, when I try to move a submenu up to the previous level, it wont drop into place. (This is not due to the vertical movement issue I mentioned above) 
https://cloudup.com/cSfJqEnf34w

Menu Customizer: Version 0.6-20150615
WP: 4.3-alpha-32775

**Comment by ocean90** [comment]
Thanks for testing!

> As soon as you move a single menu item, the live preview breaks

Twenty Fifteen requires a change for this which isn't committed yet. See https://core.trac.wordpress.org/attachment/ticket/32576/32576.menu-customizer-core-misc.diff.


> Can't move certain submenus up a level. 

That's because the menu item has another sibling, the same happens on wp-admin/nav-menus.php too.

**Comment by designsimply** [comment]
Drag and drop and live previews have been fixed. I'm going to close this issue, but please re-open if you're still having trouble with WordPress r32806 (the plugin is no longer needed).
