### ISSUE TITLE
UI: Remove icons from Delete and Original link

### ISSUE THREAD

**Issue by ocean90** [voldemortensen/menu-customizer#115]
![image](https://cloud.githubusercontent.com/assets/617637/8167560/5dc05c14-139f-11e5-8369-ff68482b9935.png)

* Core doesn't use additional icons for links.
* The icon for the Original link looks like clicking on it will open the link in a new tab/window, but it doesn't.

**Comment by valendesigns** [comment]
Now that the link stays in the Customizer it makes sense to remove it. I removed the X at one point but someone added it back.
