### ISSUE TITLE
Menu items are lost if a new menu is assigned to a location

### ISSUE THREAD

**Issue by ocean90** [voldemortensen/menu-customizer#116]
Steps to reproduce:

* Activate Twenty Fifteen
* Open Menu Customizer
* Create a new menu "Social"
* Add a custom link with "https://twitter.com/ocean90" as URL and "Twitter" as Link Text
* Close available menu items
* Check the checkbox for  "Social Links Menu"

Now the menu items are gone, but the menu is correctly live-previewed.

Tested in master and feature/issue-111.

**Comment by westonruter** [comment]
The issue where was addressed previously for the `MenuControl` but I didn't do it for `MenuItemControl`. For dynamically-created controls, especially these ones for menus which aren't added in PHP, will not be exported from the preview back to the pane among the `activeControls`. So in your test case, when you assigned the menu to the theme location the first time, the preview refreshed and when it did, the controls were not among the `activeControls` and so the newly-created menu item control had its `active` state set to `false`. This is now fixed.
