### ISSUE TITLE
Should the checkbox turn back into a plus sign if you add an item and then immediately delete it?

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#117]
When you add a menu item, the `+` icon becomes a checkbox icon as soon as the menu item is added, but that checkbox does not turn back into a plus sign symbol if the item is then removed via quick-delete. Should it?

![screen shot 2015-06-15 at mon jun 15 3 32 40 pm](https://cloud.githubusercontent.com/assets/1119271/8168865/e4381f88-1373-11e5-8c31-6bda930c52a2.png)

Example screencast: [22s](https://cloudup.com/cqdfbxIeq9R)
<sup>Tested with WordPress 4.3-alpha-32784 and Menu Customizer plugin 0.6-20150615 on Firefox 38.0.5 on Mac OSX 10.10.3.</sup>

/hat tip for the original report from Anthony Hortin at https://wordpress.org/support/topic/confusing-label-on-added-menu-items?replies=2

**Comment by valendesigns** [comment]
It would seem like the right thing to do, but since you can add the link multiple times what happens in that situation?

**Comment by designsimply** [comment]
Good question. I feel like it still might be confusing for an edge case like that, however, I think your question hits a pretty edge case (my assumption being that people don't often add the same menu item multiple times). 

Switching back to a plus sign symbol might help make the more typical action (adding an item one time per menu) more clear when the menu item is removed. However, I would only advocate for it at this stage if it's an easy update development-wise. I don't think it's a blocker. It's also something I can try to watch out for in user testing.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32689
