### ISSUE TITLE
IE8 issues

### ISSUE THREAD

**Issue by ocean90** [voldemortensen/menu-customizer#119]
Edit: This issue belongs to all sections and is probably an issue with https://core.trac.wordpress.org/ticket/31336
![image](https://cloud.githubusercontent.com/assets/617637/8170453/f3d91c98-13b0-11e5-9e22-3c170218c786.png)

**Comment by ocean90** [comment]
![image](https://cloud.githubusercontent.com/assets/617637/8170465/02b98ce8-13b1-11e5-8db4-199070851c5c.png)

**Comment by afercia** [comment]
IE 8 doesn't understand `calc()`, providing a % width or in pixels will fix the first issue in the first screenshot:
```
/wp-admin/css/customize-controls.css

#customize-theme-controls .accordion-section-content {
	margin: 0;
	position: absolute;
	left: 100%;
	top: 0;
	width: IE 8 width here; <--
	width: -webkit-calc(100% - 24px);
	width: calc(100% - 24px);
	padding: 12px;
}
```

About the second issue, looks like `.menu-item-handle` is inheriting from `/wp-admin/css/nav-menus.css` a 382px width not sure why IE 8 doesn't get the override in
```
.wp-customizer .menu-item-bar .menu-item-handle {
	max-width: 100%;
```
changing max-width in width fixes it.

**Comment by designsimply** [comment]
Closing this and moving to https://core.trac.wordpress.org/ticket/32664
