### ISSUE TITLE
Dropzone targets are stuck at the top in unsaved menus

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#121]
Steps to reproduce:

1. Go to Appearance > Customize > Menus
1. Click the "Add a Menu" button, give the menu a name, and click the "Create Menu" button
1. Click the "+ Add Items" button
1. Add several menu items and try to drag and drop them into various positions including into the first position, last position, and into a submenu

<strong>Result:</strong> I can drag and drop to rearrange items, but the dropzone target always appears in the same place above the menu where it shouldn't be and it's really hard to drop items into the space where I want them to go.

Screencast: [1m55s](https://cloudup.com/cRI689H7oWJ)

![screen shot 2015-06-15 at mon jun 15 7 55 39 pm](https://cloud.githubusercontent.com/assets/1119271/8173440/7138c97e-139b-11e5-80c6-77e6c0faea5c.png)
<sup>Seen at http://whatisinfinity.com/wp-admin/customize.php tested with WordPress 4.3-alpha-32784 and Menu Customizer plugin 0.6 287485c using Firefox 38.0.5 on Mac OSX 10.10.3.</sup>

**Comment by westonruter** [comment]
@adamsilverstein can you investigate?

**Comment by adamsilverstein** [comment]
I'm looking into this now.

**Comment by adamsilverstein** [comment]
This is fixed in [this commit](https://github.com/voldemortensen/menu-customizer/commit/1669b34bd0b5163386fcb811e8723f31dec326df) - the issue was the id assigned to the accordion section ended in -menu vs -nav_menu, breaking the targeting for the critical placeholder css targeting.

**Comment by adamsilverstein** [comment]
@designsimply this fix is merged to master, and making it into the core merge as well :)

**Comment by designsimply** [comment]
Sweet. Re-tested using WordPress 4.3-alpha-32812 (no plugin!) and it's smooth like butter.  :+1:
