### ISSUE TITLE
Extra spacing at the top of an unsaved menu panel just after a menu is first created

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#122]
Steps to reproduce:

1. Go to Appearance > Customize > Menus
1. Click the "Add a Menu" button, give the menu a name, and click the "Create Menu" button
1. Look at the area above the panel heading

<strong>Result:</strong> there's an extra 45px top margin causing a gap at the top of the menu panel that shouldn't be there. If you close the menu panel and re-open it, the gap goes away.

Screencast: [1m15s](https://cloudup.com/cBGHjnzAvNY)

![screen shot 2015-06-15 at mon jun 15 8 12 02 pm](https://cloud.githubusercontent.com/assets/1119271/8173406/f1b42b44-139a-11e5-8977-d9631103e48e.png)
<sup>Seen at http://whatisinfinity.com/wp-admin/customize.php tested with WordPress 4.3-alpha-32784 and Menu Customizer plugin 0.6 287485c using Firefox 38.0.5 on Mac OSX 10.10.3.</sup>

**Comment by ocean90** [comment]
The 45px are coming from https://github.com/xwp/wordpress-develop/blob/master/src/wp-admin/js/customize-controls.js#L608

**Comment by designsimply** [comment]
Closing this and moving to https://core.trac.wordpress.org/ticket/32662
