### ISSUE TITLE
Delete menu confirmation asks if you want to make the change permanent, even though it's not permanent

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#123]
In the delete menu confirmation, it asks you if you are sure you want to permanently delete the menu. However, after recent updates, the delete action is no longer permanent until you click "Save & Publish" in the customizer, so should it still say "permanently"?

![screen shot 2015-06-15 at mon jun 15 8 32 33 pm](https://cloud.githubusercontent.com/assets/1119271/8173596/0440d28c-139e-11e5-96f9-c6df15cdd177.png)
<sup>Seen at http://whatisinfinity.com/wp-admin/customize.php tested with WordPress 4.3-alpha-32784 and Menu Customizer plugin 0.6 287485c using Firefox 38.0.5 on Mac OSX 10.10.3</sup>

**Comment by westonruter** [comment]
No, it should not say "permanently". Additionally, we don't even need the AYS dialog anymore.
