### ISSUE TITLE
How do you remove the menus customizer panel from the customizer admin?

### ISSUE THREAD

**Issue by talymo** [voldemortensen/menu-customizer#128]
I have no editable menus on my page and I have no need for this and don't want it cluttering up the admin section of the customizer. 

I've tried adding
 $wp_customize->remove_panel( 'menus' ); 
but that does not work. 

I've also tried about 50 variations of that with no success. 

How can I get rid of this thing?

**Comment by westonruter** [comment]
@talymo hi there. Since Menu Customizer has been merged into Core, this plugin should no longer be used. In order to turn the feature off in Core, please see: https://core.trac.wordpress.org/ticket/33552
