### ISSUE TITLE
Duplicate menu names results in silent failure

### ISSUE THREAD

**Issue by curdin** [voldemortensen/menu-customizer#17]
When creating a menu, such as "mymenu" an ajax call is made that returns a json object similar to {"name":"mymenu","id":11} . If I create another menu called "mymenu" another ajax call is made. However this second call returns an empty response. Menu-customizer doesn't know how to deal with this response and continues to show the loading graphic next to Create Menu. 
![image](https://cloud.githubusercontent.com/assets/31509/5993521/ef18dee8-aab8-11e4-8fc6-7600ac11105b.png)

**Comment by celloexpressions** [comment]
We need to add error handling for when invalid menu names are submitted. This will most frequently happen when there's a duplicate menu name, which is this case.

**Comment by valendesigns** [comment]
This is fixed in the PR I just submitted.

**Comment by voldemortensen** [comment]
We can close this once the pull request is merged.
