### ISSUE TITLE
Adding sub-menu items always gets added as a child of the first menu and unable to change sub-menu level

### ISSUE THREAD

**Issue by DevelopOnline** [voldemortensen/menu-customizer#18]
Hi there,
First off all I congratulate you for your amazing idea :+1: 
I have investigated this plugin, and I found that when I add a new item to menu as sub-menu, regardless of its parent & it's location it will be the child of first menu item.
I tried to change the sub-menu item that mentioned above using `Reorder` and `Drag & Drop`, but sub-menu item's location didn't change.
Any Solution?!

Thanks in advance

**Comment by designsimply** [comment]
@DevelopOnline, when I add a new item, it always gets added to the bottom of the list. I also tested changing a sub-menu into a top-level item using `Reorder` and it worked for me. Using `Drag & Drop` to change submenu levels is not supported yet, but it's a planned update! See #4.

Can you please try testing again with the latest version of the plugin and let me know if you're still having trouble?

<sup>I used WP 4.3-alpha-32600 and the <a href="https://github.com/voldemortensen/menu-customizer">Menu Customizer</a> 0.4 (6a6fca3) on Firefox 38.0.1 on Mac OSX 10.10.3 in my tests.</sup>

**Comment by celloexpressions** [comment]
I"m going to close this for now, please reopen if you're still having issues @DevelopOnline.
