### ISSUE TITLE
Improve "Original" links

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#20]
Inside a menu item control the original page title is displayed with a link for non-custom menu item types. Currently it as a visual icon indicating that the link will open in a new tab, but we would need to ensure that that information is also provided in an accessible manner if it stays that way. A possible alternative would be to try making the page open in the Customizer preview rather than linking it off in a new tab. I'm not sure if there's a good way to do this currently, but it could definitely be a valid use-case for other things too, so we could also look into adding direct core support for changing the preview URL from the Customizer Controls window. Anyone have thoughts on this?

**Comment by valendesigns** [comment]
Couldn't we attach a click event that fools the Customizer into thinking we have clicked within the frame and not a control?

**Comment by celloexpressions** [comment]
I feel like there's probably a way to change the preview URL directly from the Customizer, but I'm not sure how. Likely in customize-base.js or somewhere in the less-structured parts of customize-controls.js in core.

**Comment by valendesigns** [comment]
Looking in those files it seems like `Loader.pushState` in `customize-loader.php` might be what we need, but I'm not sure how to use it.

**Comment by valendesigns** [comment]
Does anyone know how to use `Loader.pushState` from outside of that file? I'm just not familiar enough with the code base yet to guess.

**Comment by voldemortensen** [comment]
I've almost got this implemented. Just working on a few kinks and I'll have it ready to go.
