### ISSUE TITLE
Redesign the screen options popup

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#21]
The screen option popup is currently based on an old design mockup for the admin where screen options were presented on a dark background and attached to the admin bar. Since that happens, we should figure out a way to make this UI work better in a light version.

**Comment by celloexpressions** [comment]
Could potentially slide it down where the panel description shows up when toggled with the new help button in #31336.

**Comment by valendesigns** [comment]
I literally 15 minutes ago just noticed that this was a toggle for essentially screen options. This definitely needs to be more self explanatory and that you can add other inputs.

**Comment by celloexpressions** [comment]
I wonder whether it would help if core moved to actually using that icon, as was proposed at least 2 years ago (there's a trac ticket somewhere). Either way, should be easy to cleanup when we do the custom panel after #31336 lands. Hopefully pairing it an unifying the experience with the help icon will help. I'd love to not have these options at all, but we have to have the functionality and at least they're all off by default.

**Comment by valendesigns** [comment]
It should match the default UX for menus in Core as much as possible. Which ones are on by default there?

**Comment by celloexpressions** [comment]
The only one that is is title attribute and that's not for a good reason (per nacin just for visual balance) and increasingly being discouraged anyway. The options do cross-sync too, so that's good. Seeing as screen options in general are a struggle for users, I think pretty much anything we do here should make it at least a bit more discoverable.

**Comment by valendesigns** [comment]
After the most recent pull the pop up isn't working anymore and we have a build fail which can be easily solved.

**Comment by celloexpressions** [comment]
Oops, feel free to fix if you're able. Still working on git workflows

**Comment by valendesigns** [comment]
OK, no worries.

**Comment by valendesigns** [comment]
I'll start a PR so I can test build passing.

**Comment by valendesigns** [comment]
I'm not sure exactly where to begin with the pop-up breaking. It's not obvious how it's being built in the first place any insight into where to begin would be great. Otherwise, I'll have to leave it for now.

**Comment by celloexpressions** [comment]
I'm inclined to just leave it until we fix the way it's handled in general, it's really bad right now. We need #31336 to be committed to core first, though.

**Comment by valendesigns** [comment]
I'm almost done with this UI. The discussion around the design is happening in slack. As well, I figured out what was broken. The `WP_Menu_Options_Customize_Control` section was set to `nav` instead of `menu_locations`. It came back once I found that.
