### ISSUE TITLE
Different menu deletion UI

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#25]
Core ticket #31336 will greatly improve the Customizer UI including for menus, but we will need to adjust a few things. Notably, the current menu-deletion UI relies on all menus being visible while the add new section is open. We could just make the add new section accordion instead of the new sliding thing, but the current UI isn't great either. I'm open to suggestions, but currently thinking a `<select>` with each of the menus that aren't assigned to any locations available to pick from, and that is only visible after clicking the delete a menu in the add new section.

**Comment by valendesigns** [comment]
I am currently working on changing the delete UI as it's really bad. I'll have it done in the next couple hours.

**Comment by valendesigns** [comment]
Actually, I believe I'm done with that. You can see it here https://github.com/valendesigns/menu-customizer/commits/feature-code-cleanup

I'm working on a bunch of different things which I'll need to create a PR for likely tomorrow evening. In the meantime you can test the updated UX for deleting menus and see if it's inline with what you had in mind.

**Comment by celloexpressions** [comment]
Remaining thing: let's hide it if the menu is in use in a theme location.

**Comment by valendesigns** [comment]
That's a great idea. I'll work on it of nobody else is currently. Also, we should implement a way to assign these tickets so we know who is doing what.

**Comment by celloexpressions** [comment]
You should be able to add something to what I did in #24 that does this (watch out for the possibility of one menu in multiple locations when dynamically removing what will probably be a class that hides it). Let's not worry about menus in widgets, although that is also a possibility, but I think it's best to just hide it if it's in a theme location.

**Comment by celloexpressions** [comment]
Oh, and it looks like you need to be added to this repo or something to be able to assign/be assigned... @voldemortensen can you do that?

**Comment by valendesigns** [comment]
I'll still work in my repo and do PR's, but that would make things a lot more organized.

**Comment by voldemortensen** [comment]
@valendesigns, you're added to the repo now. Just so you're aware of how we've been doing things, any of your development should be done in a branch. You can commit the branch straight to this repo and create a PR from the branch.

**Comment by valendesigns** [comment]
Ah sweet, sounds good. Much easier process than what I'm currently doing. Thanks Garth!
