### ISSUE TITLE
New menu cannot return to the menus panel

### ISSUE THREAD

**Issue by valendesigns** [voldemortensen/menu-customizer#34]
When the patch from #31336 is applied there isn't a return path to the menus panel when you create a new menu. So you have to exit the customizer.

**Comment by celloexpressions** [comment]
The best solution for this is to get https://core.trac.wordpress.org/ticket/30737 committed to core. We can back port a bunch of stuff and roll our own fix, but it should really just be done in core. I'll refresh the patch and update the milestone there, but someone will need to add quint tests before it will be committed.

**Comment by celloexpressions** [comment]
This is now fixed, although new theme sections need some UI tweaks, let's finish off 30737 before evaluating further.
