### ISSUE TITLE
Custom Panel to integrate screen options functionality

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#36]
Once [#31336](https://core.trac.wordpress.org/ticket/31336) is done, let's create a custom panel that re-implements our screen options functionality in a more integrated way, potentially also making it reusable for other plugins' panels.It's currently extremely hacky.

**Comment by designsimply** [comment]
For reference, here is how screen options look for Menus in the dashboard on WP 4.3-alpha-32600 on Firefox 38.0.1 and Safari iOS 8.3 on iPhone 6:

![screen shot 2015-05-27 at wed may 27 11 33 57 am](https://cloud.githubusercontent.com/assets/1119271/7840310/c4f28dca-0464-11e5-98be-eb812e8917e7.png)

<img alt="img_2568" src="https://cloud.githubusercontent.com/assets/1119271/7840399/2eeebf82-0465-11e5-9ca9-7a7944392746.png" width="300" />

<sup>Plugin version: <a href="https://github.com/voldemortensen/menu-customizer">Menu Customizer</a> 0.4 (6a6fca3)</sup>

**Comment by valendesigns** [comment]
Punting. We need to focus on bugs, this already works in its current start without creating a custom panel.

**Comment by celloexpressions** [comment]
This code is atrocious. We really shouldn't be merging things into core that aren't anywhere near best practices. Committers/lead devs _should_ object to this in its current state, and I don't want to try to sneak it in around them, because I agree that it's really bad (keeping in mind that I wrote this code). I'll take a look tonight now that 31336 and 30737 are resolved - I don't think it'll be much work to do and I know how to do it.
