### ISSUE TITLE
Tracking: Core ticket dependencies

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#37]
Core tickets referenced here are dependencies for the plugin to be considered for core merge, and require at least a first-pass to be committed before a merge patch could be created. We need help on working on these ticket/patches as badly as we need help on the plugin itself.

[#31336](https://core.trac.wordpress.org/ticket/31336): Customizer: separate navigation from options UI for better UX by removing accordion behavior **CRITICAL**
[#30737](https://core.trac.wordpress.org/ticket/30737): JS templates for Customizer Panels and Sections **CRITICAL**
[#30738](https://core.trac.wordpress.org/ticket/30738): JS content templates for base WP_Customize_Control **Requires extensive workarounds if we don't do it**
[#30741](https://core.trac.wordpress.org/ticket/30741): Build-out API for adding Customizer Panels, Sections, and Controls entirely with JS **Requires extensive workarounds if we don't do it**

Note: these four need to be done in this listed order (they're all cross-dependent). More can be added to this ticket as we find them.

**Comment by westonruter** [comment]
@celloexpressions Can you provide links to the code snippets showing the current workarounds in place for #30738 and #30741?

**Comment by westonruter** [comment]
`#31336` has been merged.

**Comment by westonruter** [comment]
`#30737` has been refreshed. Once it is committed (in a few hours) we'll need to update Menu Customizer to make use of the changes in Core. @valendesigns volunteered.

**Comment by celloexpressions** [comment]
Going to close this for now, as the critical ones have been resolved. There will be some usability quirks after merge that make it advantageous to do #30738, and then we'll see where we land with #30741, which will be more about polishing the API side of things.
