### ISSUE TITLE
API for adding menu item fields

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#38]
Rather than simply providing actions and filters for adding things to menu item controls, due to the complexities involved with handling previewing and saving there should be a basic API for adding fields to menu item controls.

While this is not necessarily required, it would be really nice to implement alongside Menu Customizer, especially since it's no longer possible to add fields by using a custom walker. May want to wait for a future core release to leverage the in-progress Fields API, though, or set it up in a way that that can be used in the future.

**Comment by westonruter** [comment]
I suggest we punt this.

**Comment by westonruter** [comment]
I'll close this one as a duplicate. This has been reported in #103, and I've followed up there with tentative implementation steps.
