### ISSUE TITLE
Missing controls in new menus

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#39]
Menu name, theme locations and auto-add new items checkboxes aren't currently added to new menus. We can either roll our own hack and/or custom controls to work around this, or patch and commit to core http://core.trac.wordpress.org/ticket/30738.

**Comment by celloexpressions** [comment]
We really shouldn't merge into core with custom controls that do things that the core controls do - that will cause API fragmentation as people start using the other ones and make it difficult to get back together. @valendesigns do you think you could look at finishing the patch I started for 30738 (posted it in slack) and work from that? I can help out here too. It really isn't that much more effort than trying to work around the issue, may even be easier.

**Comment by celloexpressions** [comment]
Due to timing, we're going to need to wait until after core merge to fix this, since it depends on the core ticket being fixed.

**Comment by westonruter** [comment]
This was fixed in #73. Note that custom controls are needed because the values for the controls' input are synced with properties of the shared setting, as opposed to the entire setting itself.
