### ISSUE TITLE
"Add links" does not work on small screens like iPhone 5

### ISSUE THREAD

**Issue by valendesigns** [voldemortensen/menu-customizer#40]
The panel needs to slide in. Currently the panel stays hidden from view.

**Comment by celloexpressions** [comment]
This should wait for #31336 and copy/paste the CSS from Widgets, as well as the mobile add-panel header.

**Comment by designsimply** [comment]
For reference, here's a screenshot showing this problem which happened for me on an iPhone 6 right after tapping the "+ Add Links" button:

<img alt="screen shot 2015-05-27 at wed may 27 11 29 55 am" src="https://cloud.githubusercontent.com/assets/1119271/7840113/cd9425ac-0463-11e5-866c-dadffbe0a85f.png" width="400" />
<sup>Source: https://make.wordpress.org/flow/2015/05/25/testing-menus-in-the-customizer/</sup>
