### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by ocean90** [voldemortensen/menu-customizer#46]
- [ ] __construct: Rename `new_menu_ajax` to `ajax_add_menu` (Note: Preview/Persistent?)
- [x] __construct: Rename `*_ajax` to `ajax_*`
- [x] __construct: Rename `enqueue` to `enqueue_scripts`
- [x] print_templates: `esc_html__( 'Move...` should be just `__( 'Move...`
- [x] print_templates: Missing gettext function for "Add Menu Item" 
- [x] print_templates: `{{{ data.name }}}` must be `{{ data.name }}`
- [x] available_items_template: Missing gettext function for "URL", "Link Text"
- [x] available_items_template: The data attribute for an object type should be `data-obj-typ` or better `data-object-type`
- [ ] delete_menu_ajax: Each menu must have it's own nonce
- [ ] update_item_ajax: Each menu must have it's own nonce
- [ ] ~~load_available_items_ajax: `type_label` and `obj_type` should be camel case, maybe rename `type_label` to `objectTypeLabel`?~~
- [ ] `WP_Customize_Menus_Panel` , `WP_Customize_Nav_Menu_Control`, `WP_Customize_Menu_Section `, etc. We should standarize them to use `Nav_Menu` always. "Menu" for UI and "Nav Menu" in code.
- [x] Change exceptions to `WP_Error`
- [x] Remove `WP_Customize_Menus_Exception`

-

- [x] JS: `OldPreviewer` should be needed anymore
- [x] JS: Remove obsolete bug fix for `_toggleActive`

**Comment by adamsilverstein** [comment]
I'm working thru these issues.

**Comment by adamsilverstein** [comment]
Many of these issues resolved in https://github.com/adamsilverstein/menu-customizer/commits/fixes-issue-46; waiting until I can get a working  version to test with.

**Comment by adamsilverstein** [comment]
In https://github.com/voldemortensen/menu-customizer/compare/fixes-issue-46:

* Adding missing gettext functions
* Use unescaped data.name output in templates
* Remove escaping from translation
* Rename data attribute for data-object-type

**Comment by westonruter** [comment]
@ocean90:

>  load_available_items_ajax: type_label and obj_type should be camel case, maybe rename type_label to objectTypeLabel?

These snake-case names are used for consistency with the underlying `$menu_item` as prepared by `wp_setup_nav_menu_item()`.
