### ISSUE TITLE
“Currently set to” text is very hard to read on active menus

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#48]
When a menu is in hover/active state, the “Currently set to” text under a menu name turns white on very light gray and is unreadable.

![screen shot 2015-05-26 at tue may 26 12 23 21 am](https://cloud.githubusercontent.com/assets/1119271/7895483/cbe2711c-065e-11e5-8dd8-633044d1a08f.png)

**Comment by celloexpressions** [comment]
@designsimply update to latest trunk - should be fixed now that #31336 has been committed!

**Comment by designsimply** [comment]
Aha! I re-tested with WP 32658 and Menu Customizer 0.4 (425333d) and it looks better:

![screen shot 2015-05-30 at sat may 30 12 12 25 am](https://cloud.githubusercontent.com/assets/1119271/7895510/a4a980b6-0660-11e5-94ee-f7c550e30427.png)
