### ISSUE TITLE
Make item ordering based on usage instead of a random order

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#52]
The current menu item type order is:

1. Links
1. Search
1. Posts
1. Pages
1. Categories
1. Tags
1. Format

Can we change it to:

1. Search
1. Pages
1. Links
1. Categories
1. Tags
1. Posts
1. Format

Putting what we think are the most-used item types at the top?

![screen shot 2015-05-30 at sat may 30 6 27 12 pm](https://cloud.githubusercontent.com/assets/1119271/7899640/988f04c4-06f9-11e5-8879-7c337ca9e3d7.png)
<sup>Tested with WP 4.3-alpha-32629 and [Menu Customizer](https://github.com/voldemortensen/menu-customizer) plugin 0.4 (51d2682) with Firefox 38.0.1 on Mac OSX 10.10.3.</sup>

**Comment by celloexpressions** [comment]
Implementation-wise we can easily switch search and links. Beyond that, it's going to be difficult. We may be able to change the order within post types or within taxonomies, but any sort of mixing could be disastrous. Also need to consider that custom post types and taxonomies will also be added to this, perhaps we should make them screen-optional, like they are in the admin? I'd like to see at least post format off by default.

**Comment by designsimply** [comment]
I see the order has been updated:

![screen shot 2015-05-30 at sat may 30 8 38 57 pm](https://cloud.githubusercontent.com/assets/1119271/7900002/00738eb8-070c-11e5-8af4-783e54417ef2.png)

Are you sure Links shouldn't be at the bottom? I think it will still be easy to spot there.

Any chance you can make Pages come before Posts? Posts really aren't a common item to add to a menu. I would put them last even.

**Comment by valendesigns** [comment]
We can move links to the bottom, but that would be the only change we can make. The current limitations are not very extensible and hold us back from doing any sorting.

**Comment by celloexpressions** [comment]
Closing this out for now - there isn't really a good way to change this further from a technical perspective, and the current layout is probably the best as links are definitely more frequently used than most taxonomies and even post types. We can always revisit in core trac in the future.
