### ISSUE TITLE
Cannot delete new menus previously set to a menu location

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#57]
Steps to reproduce:

1. Go to Customize > Menus on a blog with at least one previously saved menu
1. Create a new menu and add an item to it
1. Assign the menu you just created to a menu location
1. Assign a different menu to the same menu location
1. Try to delete the new menu

<strong>Result:</strong> I can't delete a new menu that has been set to a menu location at any point in the customizer session: [1m52s](https://cloudup.com/cOSmnTX0pgE)

![screen shot 2015-05-30 at sat may 30 8 14 12 pm](https://cloud.githubusercontent.com/assets/1119271/7899964/f791d424-0708-11e5-8dd3-9d1b7c17b2bf.png)
<sup>Tested with WP 4.3-alpha-32659 and Menu Customizer 0.4 (eec366f) on Firefox 38.0.1 on Mac OSX 10.10.3.</sup>

Arguments against this change:

* you don't really need to delete menus if you aren't using them, and it's often better not to
*  menu deletion is not reversible, unlike pretty much everything else you can preview

Posting the issue because it's frustrating to bump into this and be stuck unable to change something without knowing why it's like that. However, the arguments against are strong too, and it's not a super important flow, so I'll defer to you to decide whether to punt this issue.

**Comment by samuelsidler** [comment]
Here's a quick screencast of the issue including a page refresh in there to make delete possible again.

![untitled 2](https://cloud.githubusercontent.com/assets/4642604/7986271/9068892e-0aa4-11e5-8fdf-161da7e9b1ac.gif)

I generally think that if you Save & Publish, having removed the menu from any menu locations, you should be able to delete it. However, you should _not_ be able to delete it _before_ a Save & Publish, and I even think it's fine to require the user to go up a level and back to the menu.

Note that this behavior differs from the backend menus screen when you can delete a menu at any point, regardless of whether it's in use or not. Perhaps we should just copy that?

**Comment by celloexpressions** [comment]
If we want to make this perfectly seamless - only allowing delete once the settings have been saved, we could just bind into the Customizer `saved` event. But if menu-deletion is made previewable, and we only hide the button on actively-in-use (in the preview) menus, would that work (based on what @westonruter is working on)? I'd generally like to avoid making menu-deletion a very prominent feature, as many users/sites will never need to use it at all.

**Comment by westonruter** [comment]
Yes, menu deletion is previewable now: https://github.com/voldemortensen/menu-customizer/blob/80797fed538f0db76e6b0b3b33d847ee3a4d8130/tests/test-class-wp-customize-nav-menu-setting.php#L238-L270

The way a menu (or menu item) gets deleted is for its setting value to be set to `false` (as opposed to the new-normal array containing the object's properties).

**Comment by westonruter** [comment]
@designsimply I think this is fixed now.

**Comment by designsimply** [comment]
:+1: Tested and confirmed fixed with WP 4.3-alpha-32280-src and Menu Customizer plugin 0.6-df789de. Thanks!
