### ISSUE TITLE
Make a menu setting "dirty" whenever an item in it is updated (depends on #67)

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#6]
Since menu item updates don't change the value of any settings after they're changed the first time between saves (when it's cloned and gets a new id), the preview doesn't seem to be updating when their fields change with 4.1. @westonruter should probably look at this one.

**Comment by kucrut** [comment]
Based on my [findings](https://github.com/voldemortensen/menu-customizer/commit/f6fec3fe69f31a54e7570430599f41f1e972f4b2), I believe we need a *pre* filter hook in `wp_get_nav_menu_items()` a-la `get_option()`'s to make the preview working for newly created nav menus.

**Comment by westonruter** [comment]
This would be fixed by https://github.com/voldemortensen/menu-customizer/issues/67

**Comment by westonruter** [comment]
This is being fixed now in the PR for #67.
