### ISSUE TITLE
Cannot delete menus when using Firefox

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#60]
Steps to reproduce:

1. Go to Customize > Menus
1. Create a new menu or open a pre-existing menu
1. Click the "Delete menu" link

<strong>Result:</strong> nothing happens when I click the delete link in Firefox 38.0.1. Works fine on Chrome 43.0.2357.65. Here's the error from the console in Firefox after clicking delete:

> ReferenceError: event is not defined  menu-customizer.js:2046:0 menu-customizer.js:2046:0

![screen shot 2015-05-30 at sat may 30 9 24 31 pm](https://cloud.githubusercontent.com/assets/1119271/7900120/4b920440-0713-11e5-9c19-0a634949b3b0.png)
<sup>Tested with WP 4.3-alpha-32280-src and Menu Customizer plugin 0.4 (6195629) and Firefox 38.0.1 on Mac OS X 10.10.3.</sup>

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/voldemortensen/menu-customizer/pull/69
