### ISSUE TITLE
Todo audit

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#66]
There are tons of @todos throughout the Menu Customizer codebase. We need to clean them up now. If it's critically missing functionality it gets a new issue and an owner to fix it. If it's a question let's discuss it in Slack and make a decision. If it's referencing a core dependency, let's keep it for now.

**Comment by celloexpressions** [comment]
`class-wp-customize-menus.php`:
165: // @todo: do we really need this - do we need to populate the description field here? (note: copied from existing core system)
**I'm pretty sure we can remove the code here, will do so tomorrow unless anyone objects.**
507: //'theme_supports' => 'menus|widgets', @todo allow multiple theme supports
**We really need something here - Menus should be shown if menu locations exist _or_ widget areas exist, or both. We shouldn't restrict it to just menus support. May need to wait until after merge, need a decision here.**
511: @todo core merge remove corresponding code from WP_Customize_Manager::register_controls().
**Thing for core merge list.**
525: // @todo if ( ! $menus ) : make a "default" menu
**Need to decide if we want/need a default menu. There was some discussion in #core-customize, but no consensus yet. Will wait until after merge at this point.**
587: // @todo we need to implement something like WP_Customize_Widgets::prepreview_added_sidebars_widgets() so that wp_get_nav_menu_items() will include the new menu items
**No idea about this one, @westonruter?**
1104: // @todo: consider using add_meta_box/do_accordion_section and making screen-optional?
**This is in reference to the available item type sections. I think we should probably wait if we decide to do it.**
1270: // @todo Instead of throwing Exceptions, we'll have to switch to passing around WP_Error objects.
**No idea, @westonruter?**



`menu-customizer.js`:
804: @todo handle removal when theme location is set to blank.
**This definitely needs to be fixed. Shouldn't be hard**
1158: // @todo replace this with wp.ajax.post()
**I defer to @westonruter on severity/need for changing this now.
1190: // @todo this requires cloning all direct children, which will in turn recursively clone all submenu items - works, but is there a better approach?
**Not good, but works for now. Type of thing that would likely be fixed in a beta if it brings up major issues anywhere.**
1195: // @todo There should really be Customizer settings that contain all of the menu item fields
**Yes, but is that something we can change at this point?**
1353, 1355, 1371, 1373, 1410: **We need to fix some issues with reordering menu items and submenus. Well, two major issues, each for up and down. It's doable but probably a lot of code.**
1924: // @todo: Instead of {}, the initial setting should have an ID, title, and menu_item_parent
**It works, but ideally we'd fix this.**
2063: // @todo core this shouldn't be necessary.
**Latest patch on #30737 should fix this
2080: // @todo core should do this for us
**#30741 would fix this, among other things.**
2093, 2094: **Need #30738 to fix this (adding missing controls to new menus)**
2112: // @todo should we focus on the new menu's control and open the add-items panel? Thinking user flow...
**Discussed this with @designsimply, I think we'd like to try testing both ways with new users. Can wait for now.**
2150: // @todo core there should be API methods for deleting sections.
**I think there are now? Let's use them (this was pre-4.1).**

**Comment by celloexpressions** [comment]
Need someone to take another pass through all of the todos in the codebase now - most of the ones above have been resolved but others have been added. We should ideally not have many when merging.

**Comment by designsimply** [comment]
Closing and moving to https://core.trac.wordpress.org/ticket/32663
