### ISSUE TITLE
Accessibility: Make Some Links Buttons

### ISSUE THREAD

**Issue by davidakennedy** [voldemortensen/menu-customizer#75]
This was noted in #50, but it would be great if a few `<a>` elements were made `<button>` elements instead for clearer use with a screen reader.

A few good candidates:

* The "plus" symbols here, which are in multiple places: https://cloudup.com/ceCyc8uBGYj
* The "Remove" link here, which are also in multiple places: https://cloudup.com/cU8bVxOHkjI

I'll comment here if I find more. :smile:

**Comment by celloexpressions** [comment]
Thanks, I'll grab these. For background the vast majority of links in this interface are actual links in the admin, for no-JS. Just add more comments with others that should be changed.

**Comment by Cheffheid** [comment]
The spans for changing a menu item's order should probably be buttons as well.

**Comment by celloexpressions** [comment]
Feel free to open more issues if you find any others!
