### ISSUE TITLE
[BUG] new menu doesn't show in widgets

### ISSUE THREAD

**Issue by senlin** [voldemortensen/menu-customizer#80]
When adding a new menu via the Customizer and then going to the Widgets to add that new menu to a sidebar widget, this new menu does not show up. 

You first have to close the Customizer and then after re-opening the new menu shows.

**Comment by celloexpressions** [comment]
I have a feeling we may be better off fixing this after merge depending on how we decide to fix it, but I agree that this is critical functionality. We can't rely on Menus previously existing before loading the Customizer anymore.

**Comment by westonruter** [comment]
This has been fixed in 09dc8af.
