### ISSUE TITLE
Visual feedback in the add-item panel when a menu item is added

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#81]
There is currently no indication that an item is successfully added within the add-item panel, which is especially problematic on mobile but also could use improvement on larger screens where you see it show up in the menu on the left too. Thinking a label and slight fade over added items in the panel that's semi-persistent - clears each time the panel is closed.

**Comment by folletto** [comment]
I'd avoid making anything "persistent until close", unless it's "until Save", but even there would be a behaviour unique on the menus and I'm not entirely sure of the benefits.

What could work really well would be an animation when the item gets added, either as a _fade in_ (`opacity: 0.0 → 1.0`) or a _fold open_ (`height: 0 → Y`). Fold open works better but might be slightly more difficult to implement in my experience.

That animation alone I feel would solve the problem entirely. :)

**Comment by celloexpressions** [comment]
Note that the menu itself isn't visible on mobile since the add-item panel is on top of it. So we can't actually see the menu item get added in that case. Not sure whether the added is needed on larger screens, but seems like it can't hurt. Fading it out after a few seconds would probably do it.

Could definitely also improve the animation of the item being added, as it's kind of broken right now, jumps to the top then the bottom, etc. I wonder if adding the control as deactivated then activating it could give us that slideIn effect? Problem is there's a loading placeholder currently too.

**Comment by folletto** [comment]
> So we can't actually see the menu item get added in that case.

Yes we can! :D 
It needs to happen when you switch back, not instantly. ;)

**Comment by celloexpressions** [comment]
See https://make.wordpress.org/flow/2015/06/04/menu-customizer-iphone-6/. I did exactly thee same thing the first time I tried it on a phone. The only option here is to add some sort of feedback within the add-item panel as soon as an item is clicked/tapped.  Thinking a 5s (or whatever) delay then fadeout would work, and we can decide to always show it or only on mobile where you can't see it actually get added.

**Comment by folletto** [comment]
Ahh. I'm sorry. I thought this ticket referred to the item added once you were back from the add-item screen, not on the add item screen _itself_. Sorry!

Then yes. Let's just have a simple puls animation. Is there anything else already in WordPress that does something similar, or do we have to make it from scratch? If it's the second I can probably mock something up. ;)

**Comment by celloexpressions** [comment]
Here's a screenshot of what it currently looks like. Couldn't find anything like this in core.

![menu-customizer-item-added](https://cloud.githubusercontent.com/assets/7875961/8083830/4e62c6d8-0f3c-11e5-9bb9-70008e23c70d.png)

**Comment by folletto** [comment]
Here's an idea:

![licecap-](https://cloud.githubusercontent.com/assets/4389/8106392/34de1266-1041-11e5-91c3-fbeff05d2713.gif)

Check the [CodePen demo here](http://codepen.io/folletto/pen/pJwrYp).

**Comment by valendesigns** [comment]
That looks much better. +1

**Comment by celloexpressions** [comment]
This works great, about to commit. The dasicon size is super awkward - the + icons are way to big & heavy, but the check is too small. But, trying to align them size-wise results in the infamous issue of icon fonts needing to be used on the grid they're designed to, in this case 20px. Going to leave it for now, can refine after merge.

**Comment by folletto** [comment]
:+1: 

The animation needs some testing cross-browser, but should be good to add that too if possible, adding an extra visual nudge that something changed. ;)
