### ISSUE TITLE
Accessibility: doubled entries when using the keyboard

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#83]
Using the keyboard, tab to a link you want to add, and press Enter or Spacebar.
The link is added to the menu, two times.

![example]
(https://cldup.com/y9oZvaUp8Y.png)

**Comment by designsimply** [comment]
Tested and confirmed using WP 4.3-alpha-32775 and Menu Customizer plugin 0.6 (cef7fbc) with Firefox 38.0.5 on Mac OSX 10.10.3.

**Comment by designsimply** [comment]
Sounds similar to #107.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32665
