### ISSUE TITLE
UI: must click the 'Add Links' button in order to delete menu items

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#84]
As far as I see, the only way to remove a link from a menu is via the "Add Links" button. The button text says "Add Links". No clue users have to press that button to remove a link. When you're new to the Menu Customizer, you have to "discover" how to remove links, while every UI control should be self-explanatory. Sighted users will notice (after a while?) that a red cross appears on the menu items, screen reader users will be forced to "explore" any single part of the UI.

**Comment by celloexpressions** [comment]
Each item has a remove button within the menu item options when expanded, just like the admin page has. That's the primary remove functionality.

We also added the ability to quickly remove multiple items when adding items, but that's the secondary mode. Within that mode the focus is on adding items/links (might want to change to "Add Items"), but the quick-delete that accompanies it is not the primary focus so I wouldn't mention that part in the button's label.

**Comment by afercia** [comment]
Okay,being a new user, didn't consider to edit a menu item I had just added. Still, the "Add LInks" button gives you access to a "remove" functionality. A better descriptive button text would be sufficient.

About the primary mode, the point that "it's just like the admin page" doesn't mean that it's correct :) I've always considered a bit weird thing having a "remove" control inside something that says "Edit". When i find a UI control that says "Edit", I would expect to change, modify, content/settings and wouldn't expect a "delete" there,

**Comment by designsimply** [comment]
To re-cap, there are currently two ways to delete a menu item:

When the `+ Add Items` panel is open:

- You may click the red "x" to quick-delete any menu item.

When the `+ Add Items` panel is closed:

- You must click on an item to toggle it's options and then click the `x Remove` link to delete it.

@afercia, one possible reason for putting a delete action behind a toggle like this is to prevent data loss. Making it too easy to delete can sometimes lead people to accidentally delete something when they didn't want to. The quick-delete "x"s only appearing when the `+ Add Items` panel is open feels like a good balance for this, and it's a pattern that I've seen used effectively in other places (i.e. Appearance > Themes as the same pattern where you must click to open theme details before you can delete). Some users might complain and want an easier way to delete, but the pattern is in place to help prevent data loss, which I think is a good tradeoff in this case.

With this explanation, do you still feel strongly that people need a different way to delete menu items than the two options that are already in place?

**Comment by designsimply** [comment]
Labeled this as `invalid`  because I think your first assumption was you had to click add to delete, but that's not the only path. Waiting for feedback though, can definitely re-visit if there's pushback here and if afercia feels strongly about it.

**Comment by afercia** [comment]
Was just suggesting to change the button text :) 
> Appearance > Themes as the same pattern where you must click to open theme details before you can delete
Yes but the button there doesn't say "Add Theme" :) it's a generic "Theme details" text and inside that you can do different things: Activate, Preview, Delete. Same as here, you can do different things but the button says you can just "Add".

**Comment by designsimply** [comment]
<blockquote>Yes but the button there doesn't say "Add Theme" :)</blockquote>

Neither does clicking on an item to open it's options (which I think is the path you weren't considering when you originally posted).

<blockquote>you can do different things but the button says you can just "Add".</blockquote>

Even though `+ Add Items` is not the only thing you can do when you click that button, I think it's the best possible label to communicate it's main function. "Edit" doesn't cover it because it doesn't work if the menu doesn't have any items yet. What would you propose using as a label instead of `+ Add Items`?

**Comment by afercia** [comment]
> What would you propose using as a label instead of + Add Items?

Thinking at this since yesterday :) Ideally the button text should describe the set of actions made available when you press it. I understand that visually this is a minor issue since sighted users can actually see the red X. Also, I understand the troubles screen reader users will face: if they look for something to *delete* menu items, it's very unlikely they will activate a button that says "Add Items". We should try to find a good balance between visual and semantics, where the latter is not just "abstract semantics" but real information as used by software and consequently by people using that software. It's always about people :) 
If you're OK with "Add Items" for the visual part, I'd be happy to use a more descriptive  `aria-label` attribute on the button: `aria-label="Add or remove menu items"`.

**Comment by designsimply** [comment]
<blockquote>I'd be happy to use a more descriptive aria-label attribute on the button: aria-label="Add or remove menu items".</blockquote>

The `aria-label` sounds like a good idea to me.

<blockquote>I understand the troubles screen reader users will face: if they look for something to delete menu items, it's very unlikely they will activate a button that says "Add Items"</blockquote>

Do you think screen reader users would have a lot of trouble if they have to click on the item itself and then click the delete link for the item?

**Comment by afercia** [comment]
It's all about discoverability and how many key strokes are required to find a specific UI control. Finding the "delete" inside each menu item requires a bit of exploration but I think users are already used to the current Menu screens where the "Delete" placement is similar. Not saying that it's perfect but we can live with that
For accessibility, the main UI controls should be preferably grouped together that's a bit different from a merely visual approach.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32713
