### ISSUE TITLE
Accessibility: special case, the Add Links button

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#87]
The "Add Links" button, besides an aria-expanded attribute, would need also an aria-controls attribute. When the controlled panel is not immediately following the button and is very far in the source It's generally recommended to use aria-controls. For example:
```
<button type="button" class="button-secondary add-new-menu-item" aria-expanded="false" aria-controls="available-menu-items">Add Links</button>
```

**Comment by afercia** [comment]
About `aria-controls` see the notes below this example: http://heydonworks.com/practical_aria_examples/#progressive-collapsibles

**Comment by ocean90** [comment]
Moved to https://core.trac.wordpress.org/ticket/32682.
