### ISSUE TITLE
Accessibility: focus loss after a new menu is created

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#88]
Using the keyboard, create a new menu, a new panel slides in. Looks like the focus is still on the previous panel, you have to tab several times before the focus is in the new panel.

**Comment by celloexpressions** [comment]
This is actually a core issue that needs to be fixed: https://core.trac.wordpress.org/ticket/31336#comment:99. I can patch it after we merge menu Customizer if no one gets to it before then.
