### ISSUE TITLE
Accessibility: the Reorder functionality

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#94]
Some considerations about the Reorder button:
- needs a better focus style
- when pressed, there's no feedback about what's happening and about what user should do as next step
- when Reorder is pressed, the "Add Links" button is faded out but still focusable, either disable it or tabindex -1 until you're "Done"
- it's not clear the difference between "Move one level down" and "Move down" (same for "up"), consider to use a better descriptive text
- the "disabled" arrows are still focusable, announced and clickable (I think this was already reported)
- all the move arrows need a better focus style

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32725
