### ISSUE TITLE
Accessibility: the Menu Locations selects

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#95]
These selects miss a button to submit: avoid triggering page updates on change, see similar issue in Media Views discussed in core ticket #30333, I would quote Helen's comment:
https://core.trac.wordpress.org/ticket/30333#comment:5
> typically, this kind of navigation is disruptive when navigating via keyboard. The full page refresh means that focus and place are lost.

Also, browsers fire the change event in different ways, see:
https://core.trac.wordpress.org/ticket/25103#comment:7

**Comment by designsimply** [comment]
Just chiming in with a screenshot:

![screen shot 2015-06-14 at sun jun 14 6 17 29 pm](https://cloud.githubusercontent.com/assets/1119271/8150676/e152d0ae-12c1-11e5-87bc-8c3ab1eb7165.png)
<sup>Tested with WordPress 4.3-alpha-32775 and Menu Customizer plugin 0.6 (cef7fbc).</sup>

**Comment by westonruter** [comment]
> The full page refresh means that focus and place are lost.

There is no full page refresh here.

**Comment by ocean90** [comment]
Adding a button here is pretty useless in terms of the live preview.
A change doesn't force a full page refresh because it has partial refresh implemented. Also, if the preview requires a refresh the focus on the control element isn't lost, take Static Front Page as an example.

**Comment by afercia** [comment]
I disagree, kindly :) 
>>The full page refresh means that focus and place are lost.
>There is no full page refresh here.
Please don't take that quote literally, it was about a different context but the main point is valid and you can find same recommendation in pretty any accessibility guideline/resource: selects require a button. Unless users are informed before using the selects that a change will happen as soon as they change the select value.
