### ISSUE TITLE
Search results area doesn't show for single word searches

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#96]
Steps to reproduce:

1. Go to Appearance > Customize in the dashboard
1. Click menus and open a menu or create one if you don't already have one
1. Click the "Add Links" button
1. Type a single word in the search field without a space and hit Enter

<strong>Result:</strong> a spinner appears, indicating a search has happened, but the search results don't show up unless you hit the space bar at least once or if the search box loses focus. I tested with Chrome 43 and Firefox 38 on a Mac.

Screencast: <a href="https://cloudup.com/chKiF3YE-wy">41s</a>

![screen shot 2015-06-07 at sun jun 7 11 54 30 pm](https://cloud.githubusercontent.com/assets/1119271/8028014/119f5d9a-0d72-11e5-8ec6-84006e108beb.png)
<sup>Seen at http://src.wordpress-develop.dev/wp-admin/customize.php with WP 4.3-alpha-32280-src and the Menu Customizer plugin 0.5 (723de6b) using Firefox 38.0.5 on Mac OS X 10.10.3.</sup>

**Comment by celloexpressions** [comment]
Looks like this is now fixed in the feature-67 branch, can you confirm @designsimply?

**Comment by designsimply** [comment]
Tested and confirmed, search works when testing with `feature/issue-67`.
