### ISSUE TITLE
Accessibility: all form controls need a label with text

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#97]
Found the edit menu name has a label without any text, haven't checked all form controls though.
Currently:
```
<label>
<input class="menu-name-field live-update-section-title" value="Testing Menu Customizer" data-customize-setting-link="nav_menus[236][name]" type="text">
</label>
```
To my understanding, this would require something in in WP_Customize_Control to add CSS classes to the label text (the inner span, not the label itself) in order to use `screen-reader-text` and hide the label text. Maybe it's something for a core ticket?

**Comment by designsimply** [comment]
Screenshot for reference:

![screen shot 2015-06-14 at sun jun 14 6 33 39 pm](https://cloud.githubusercontent.com/assets/1119271/8150752/e9204094-12c3-11e5-9fd3-5c42220a227f.png)
<sup>Tested with WordPress 4.3-alpha-32775 and Menu Customizer plugin 0.6 (cef7fbc).</sup>

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32726
