### ISSUE TITLE
Accessibility: color contrast ratio

### ISSUE THREAD

**Issue by afercia** [voldemortensen/menu-customizer#98]
Spotted some light greys on light backgrounds which are under the minimum contrast ratio, for example `#999` on `#fff` in `.theme-location-set` or current menu location is `#999` on `#eee`. Some of them come from core CSS files.

**Comment by celloexpressions** [comment]
After some investigation, I think this needs to wait until after core merge and get broader attention in terms of changing these. We'll need to alter the design intent of the current colors quite a bit to make them meet the contrast guidelines, and they're almost all core colors.

**Comment by designsimply** [comment]
Screenshot for reference: 

![screen shot 2015-06-14 at sun jun 14 6 39 11 pm](https://cloud.githubusercontent.com/assets/1119271/8150775/d7f41a38-12c4-11e5-90cc-3bbdee298909.png)
<sup>Tested with WordPress 4.3-alpha-32775 and Menu Customizer plugin 0.6 (cef7fbc).</sup>

**Comment by designsimply** [comment]
Core ticket #29158 looks related, but I think a new issue might be needed to address things like `#999` text on a `#eee` background throughout the Customizer.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32727
